### ISSUE TITLE
It does not seem to work on Ubuntu 22.04

### ISSUE THREAD

**Issue by axthosarouris** [cankurttekin/WikiArt-Wallpaper-Gnome#1]
Not sure how to set the configuration so that the wallpaper actually appears on the desktop

**Comment by cankurttekin** [comment]
Hey, you don't set anything, just click on refresh button. It appears when you click on wikiart tray icon. did you try to refresh again? Sometimes(its very rare) there is no image for given (random) index. Do you see any errors on Extensions gui app?
What is your GNOME version? `gnome-shell --version`

> Not sure how to set the configuration so that the wallpaper actually appears on the desktop

**Comment by axthosarouris** [comment]
It does not work for the dark mode :)

**Comment by cankurttekin** [comment]
fixed with this commit: https://github.com/cankurttekin/WikiArt-Wallpaper-Gnome/commit/5869f0ceda45dbb2598b3cfdef7dcbd2f6b94628
