### ISSUE TITLE
It does not work on dark mode

### ISSUE THREAD

**Issue by axthosarouris** [cankurttekin/WikiArt-Wallpaper-Gnome#2]
Example images:
![image](https://github.com/user-attachments/assets/2f07153b-8199-4129-9014-ff5b107ff2a9)
![image](https://github.com/user-attachments/assets/b1be82f5-9301-42c2-9bd4-72543342caa1)

Gnome shell version: 42.9

**Comment by cankurttekin** [comment]
hey, thank you for reporting this. i just tried switching to dark mode indeed it does not work on my gnome 46 too. I will fix it as soon as possible.

**Comment by cankurttekin** [comment]
i pushed new version to extension.gnome.org, you will receive update soon. 
with this update extension will set wallpaper for both light and dark schema. thank you again for reporting.

**Comment by axthosarouris** [comment]
Thanks for the plugin. Nice work!
