### ISSUE TITLE
Blank Screen Issue

### ISSUE THREAD

**Issue by sushantAtwork** [cankurttekin/WikiArt-Wallpaper-Gnome#3]
### **Issue Description**

I am using **Ubuntu 22.04** with **GNOME Shell 46**. After installing the [WikiArt-Wallpaper-Gnome]  via the GNOME Extension Manager, I don't see any changes or effects. I also tried installing the extension directly from GitHub, but the issue persists.

### **Steps to Reproduce**

1. Install the extension via the GNOME Extension Manager.
2. Restart GNOME Shell or log out and log back in.
3. Verify if the extension is enabled in the Extensions app.
4. Observe that there are no visible changes.
5. Attempt to install the extension from the GitHub repository by following the instructions provided in the README.
6. Restart GNOME Shell again and check for any changes.

### **Expected Behavior**

The extension should apply the expected changes or provide the intended functionality in GNOME Shell after installation.

### **Actual Behavior**

No visible changes or effects are observed after installing and enabling the extension, even after trying both methods (via Extension Manager and manual installation from GitHub).

### **Environment**

- **OS:** Ubuntu 22.04 LTS
- **GNOME Shell Version:** 46
- **Extension Version:** [Specify the version or commit hash if installed from GitHub]
- **Installation Method:** 
  - GNOME Extension Manager
  - GitHub (manual installation)

### **Additional Information**

- I've ensured that the extension is enabled in the Extensions app.
- I've tried restarting the system

### **Screenshots**
![Screenshot from 2024-09-05 02-32-48](https://github.com/user-attachments/assets/181036d3-09a2-4848-a7ae-76f79a23c71e)

![Screenshot from 2024-09-05 02-35-34](https://github.com/user-attachments/assets/b641c267-23dc-4c7b-912f-d0a240f5ec81)

![cropped](https://github.com/user-attachments/assets/2ad37b74-cd03-434c-87e9-e4db14eb57aa)

**Comment by cankurttekin** [comment]
@sushantAtwork 
Thank you for detailed issue.
Can you show me your ext. wallpaper folder, you can open it with an option under wikiart wallpaper ext. tray icon. (its located at /home/user/Pictures/WikiArtWallpaper).
Did you try refreshing couple times?
Also posting screenshot of your Settings>Appearance window will help too.
I will try to reproduce it and fix as soon as possible.

**Comment by cankurttekin** [comment]
i am guessing its related to dark mode. I pushed to main branch with some changes. Rather than your issue it was still needed as it doesnt change wallpaper for dark mode on gnome 46 but it does on older ones but i believe this will fix your issue. waiting for feedback

**Comment by sushantAtwork** [comment]
Hi @cankurttekin, Should I switch to older version ?

**Comment by cankurttekin** [comment]
> Hi @cankurttekin, Should I switch to older version ?

no download it from github, just copy extension.js to
/home/youruser/.local/share/gnome-shell/extensions/wikiartwallpaper@cankurttekin

**Comment by sushantAtwork** [comment]
> > Hi @cankurttekin, Should I switch to older version ?
> 
> no download it from github, just copy extension.js to /home/youruser/.local/share/gnome-shell/extensions/wikiartwallpaper@cankurttekin

Sure I will, try this.

**Comment by sushantAtwork** [comment]
> > Hi @cankurttekin, Should I switch to older version ?
> 
> no download it from github, just copy extension.js to /home/youruser/.local/share/gnome-shell/extensions/wikiartwallpaper@cankurttekin

Hi @cankurttekin, I have followed the above mentioned steps, still no wallpaper.
![Screenshot from 2024-09-06 17-41-11](https://github.com/user-attachments/assets/a2341af9-6658-498b-9c05-4615393f6333)

**Comment by cankurttekin** [comment]
can you provide the extension logs, you can run nested gnome-shell with this command:
`dbus-run-session -- gnome-shell --nested --wayland`

**Comment by sushantAtwork** [comment]
> can you provide the extension logs, you can run nested gnome-shell with this command: `dbus-run-session -- gnome-shell --nested --wayland`

Hi, this is the shell ouput:
![crop](https://github.com/user-attachments/assets/939e0dd9-56f0-4d91-9a2f-1ad99b3bee2f)

**Comment by cankurttekin** [comment]
can you try it again
https://github.com/cankurttekin/WikiArt-Wallpaper-Gnome/releases/tag/v10

**Comment by greguti** [comment]
I had the same bug on my system, Ubuntu 24.04 with dark theme. I tried the WikiArt-wallpaper extension just after a fresh install and nothing happened. 

The v10 package resolved it, the wallpapers are showing at last!

![Capture d’écran du 2024-09-10 09-02-03](https://github.com/user-attachments/assets/16c8ca8d-1cda-4b0a-a347-00e95b1a20ad)

**Comment by cankurttekin** [comment]
Good to hear, i am gonna do some refactoring on v10 and after you can download it from extensions.gnome

**Comment by cankurttekin** [comment]
> I had the same bug on my system, Ubuntu 24.04 with dark theme. I tried the WikiArt-wallpaper extension just after a fresh install and nothing happened.
> 
> The v10 package resolved it, the wallpapers are showing at last!
> 
> ![Capture d’écran du 2024-09-10 09-02-03](https://private-user-images.githubusercontent.com/169248740/365930610-16c8ca8d-1cda-4b0a-a347-00e95b1a20ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzQ1MjIsIm5iZiI6MTcyNTk3NDIyMiwicGF0aCI6Ii8xNjkyNDg3NDAvMzY1OTMwNjEwLTE2YzhjYThkLTFjZGEtNGIwYS1hMzQ3LTAwZTk1YjFhMjBhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMzE3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTExMWNiNWI0NDU1YTExYzAwZDk3M2ZhMmJmNWZkMTYyYWFhYzc1YjAyNDlkNWVjOTZkYmFhYWNhZDhkMjYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3bgVCZ7xk-_Q9P9Sr2_5ea1JwTumRO1mSrGaUU0p6NQ)
